## Lesson_1_Python
for markdown cell press esc then press m

for raw cell press esc then press r

short cut for a new cell is alt + enter

In [24]:
print("the comment would not be printed") #comments are very important

the comment would not be printed

In [26]:
#normal division will get u the precise results
10 / 3

3.3333333333333335

In [28]:
#integer division 
10//3

3

In [32]:
#modulo operator returns the remainder of the division
10 % 3

1

In [ ]:
#names of variables should be separated with underscore. they should start with character
in_var = 10

ch_var = "hello"

In [39]:
print("a","b","c", sep = "✔", end = "✨")

a✔b✔c✨

In [41]:
print("You entered:", input())

 5

You entered: 5

In [47]:
input("Enter something: ")

Enter something:  5

'5'

In [64]:
print("2 == 2 is", 2 == 2)
print("2 > 3 is", 2>3)
print("2 != 3 is", 2 != 3)

2 == 2 is True
2 > 3 is False
2 != 3 is True

In [60]:
print("(2 == 2) and (3 == 3) is", (2==2) or (3==4))

print("(5==4) is", not (4==4))

(2 == 2) and (3 == 3) is True
(5==4) is False

In [1]:
if input() == "test":
    print("you have entered the word test")

 test

you have entered the word test

## Python uses identation to signify that the function belongs to the particular logical statement

In [14]:
i_value = input() 
if i_value == "test":
    print("Test")
elif i_value == "hello":
    print("hello")
else:
    print("Neither")

 nothing

Neither

In [21]:
int("1233") + 1

1234

In [23]:
float("9.5") + 0.5

10.0

In [35]:
str(1 + 0.5)

'1.5'

In [1]:
import pickle

with open("/country_data_python.pkl", "rb") as datafile:
    country_data = pickle.load(datafile)

FileNotFoundError: [Errno 2] No such file or directory: '/country_data_python.pkl'

In [69]:
list1 = ["a", 1, "b", 2, "c", 3]
list1
type(list1)

list

In [71]:
len(list1)

6

In [75]:
list1[0] #lists start with 0

'a'

In [60]:
list7 = [1,2,3,4,5,6,7,8,9,10]
list8 = list7
print(list7, "-", list8)

list8[0] = 0
print(list7, "-", list8)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] - [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 2, 3, 4, 5, 6, 7, 8, 9, 10] - [0, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [61]:
type(list7)

list

In [100]:
list2 = list1[:] #lists in python a mutable objects so they can change. this creates the shallow copy of the list1

list2.append("test") #adds the element to a list
print(list2)

list2.extend(["new1","new2"]) #extend adds a list to a list
print(list2)

list2.pop(0) #deletes the element in the list by index
print(list2)

list2.remove("new1") # deleted by name
print(list2)

print(list1)

['a', 1, 'b', 2, 'c', 3, 'test']
['a', 1, 'b', 2, 'c', 3, 'test', 'new1', 'new2']
[1, 'b', 2, 'c', 3, 'test', 'new1', 'new2']
[1, 'b', 2, 'c', 3, 'test', 'new2']
['a', 1, 'b', 2, 'c', 3]

In [114]:
list6 = [1,2,3,4,5,6,7,8,9,10]

print("[:] = ", list6[:]) #slices the whole list crating a shallow copy of the list. avoding both of the lists referring to the same list 

print("[2:] -", list6[2:]) #erases first two objects in the list

print("[:3] -", list6[:3]) #slices objects from the beginning up to the element 2 from 0 to 2

print("[::2] -", list6[::2]) #shows every nth element in the list

print("[::-1] -", list6[::-1]) #reverses a list

print("[::-2] -", list6[::-2]) #shows every second element in reverse order

print("[1:8:3] -", list6[1:8:3]) #every third element in the list starting from second element

[:] =  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2:] - [3, 4, 5, 6, 7, 8, 9, 10]
[:3] - [1, 2, 3]
[::2] - [1, 3, 5, 7, 9]
[::-1] - [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[::-2] - [10, 8, 6, 4, 2]
[1:8:3] - [2, 5, 8]

In [99]:
import pickle
import os

os.chdir('D:\py_programming\data')

with open("./country_data_python", "rb") as datafile: #do not specify the file format ,e.g. country_data_python.pkl since it was saved as country_data_python
    country_data = pickle.load(datafile)

<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
C:\Users\SEMEN\AppData\Local\Temp\ipykernel_6024\3320129275.py:4: SyntaxWarning: invalid escape sequence '\p'
  os.chdir('D:\py_programming\data')

In [20]:
type(country_data)

list

In [7]:
for point in country_data[:5]: #goes through each element in the slice of 5 elements and assigns it to the variable called point. this variable is accessible within the body of the loop. the body of the loop is run as much times as there are elements in this collection
    print(point)

{'country': 'China', 'mtCO2': 9135000000.0, 'population': 1373541278, 'GDP': 21140000000000.0}
{'country': 'United States', 'mtCO2': 5402000000.0, 'population': 323995528, 'GDP': 18560000000000.0}
{'country': 'India', 'mtCO2': 1887000000.0, 'population': 1266883598, 'GDP': 8721000000000.0}
{'country': 'Russia', 'mtCO2': 1756000000.0, 'population': 142355415, 'GDP': 3751000000000.0}
{'country': 'Japan', 'mtCO2': 1257000000.0, 'population': 126702133, 'GDP': 4932000000000.0}

In [214]:
n = 0 
while n<5:
    print(country_data[n])
    n += 1 #increases n by 1

{'country': 'China', 'mtCO2': 9135000000.0, 'population': 1373541278, 'GDP': 21140000000000.0}
{'country': 'United States', 'mtCO2': 5402000000.0, 'population': 323995528, 'GDP': 18560000000000.0}
{'country': 'India', 'mtCO2': 1887000000.0, 'population': 1266883598, 'GDP': 8721000000000.0}
{'country': 'Russia', 'mtCO2': 1756000000.0, 'population': 142355415, 'GDP': 3751000000000.0}
{'country': 'Japan', 'mtCO2': 1257000000.0, 'population': 126702133, 'GDP': 4932000000000.0}

useful for when you do not know how much iterations you need to do

In [12]:
for point in country_data:
    print(point)
    if point["country"] == "Russia": #
        break

{'country': 'China', 'mtCO2': 9135000000.0, 'population': 1373541278, 'GDP': 21140000000000.0}
{'country': 'United States', 'mtCO2': 5402000000.0, 'population': 323995528, 'GDP': 18560000000000.0}
{'country': 'India', 'mtCO2': 1887000000.0, 'population': 1266883598, 'GDP': 8721000000000.0}
{'country': 'Russia', 'mtCO2': 1756000000.0, 'population': 142355415, 'GDP': 3751000000000.0}

In [224]:
for point in country_data[:10]:
    if point["population"] % 2 == 0: #runs if statement through all points. once it is satisfied it runs the next iteration (if population modulo 2 is even we run the continue staement)
        continue
    print(point)

{'country': 'Russia', 'mtCO2': 1756000000.0, 'population': 142355415, 'GDP': 3751000000000.0}
{'country': 'Japan', 'mtCO2': 1257000000.0, 'population': 126702133, 'GDP': 4932000000000.0}
{'country': 'Iran', 'mtCO2': 650400000.0, 'population': 82801633, 'GDP': 1459000000000.0}
{'country': 'Saudi Arabia', 'mtCO2': 594000000.0, 'population': 28160273, 'GDP': 1731000000000.0}

In [229]:
us_data = country_data[1]

print(us_data)
type(us_data)

{'country': 'United States', 'mtCO2': 5402000000.0, 'population': 323995528, 'GDP': 18560000000000.0}

dict

In [231]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |
 |  Methods defined here:
 |
 |  __bool__(self, /)
 |      True if self else False
 |
 |  __contains__(self, key, /)
 |      Return key in self.
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __reduce__(...)
 |      Helper for pickle.
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __reversed__(...)
 |      Return a reverse iterator.
 |
 |  count(...)
 |      rangeobject.count(value) -> integer -- return number of occurrences of value
 |
 |  index(...)
 |      rangeobject.index(value) -> integer -- return index of value.
 |      Raise ValueError if the value is not present.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  start
 |
 |  step
 |
 |  stop

In [277]:
list(range(1,6,1))

[1, 2, 3, 4, 5]

In [335]:
var = len(input().split(";"))

if var > 5:
    print("aloha")
elif var < 5:
    print("bonjour")
elif var == 5:
    print("privet")

 t e; y t; u i; o p; y y

privet

In [329]:
type(var)

int

In [337]:
ok = "hello world" 
print(ok)

hello world

In [3]:
emails_created = [
    'ivan_petrov83@newmail.mail',
    'masha1995@newmail.mail',
    'sergey_smirnov@newmail.mail',
    'olga_ivanova@newmail.mail',
    'dmitry89@newmail.mail',
    'anna_kuznetsova21@newmail.mail'
]

not_ok = 'Choose another address for your account.'
ok = 'Your account has been successfully created!'

# YOUR CODE HERE

var = input()

if var in emails_created:
    print(not_ok)
    print(sorted(emails_created, reverse = False))
else:
    print(ok)
    emails_created.append(var)
    print(sorted(emails_created,reverse = False))

 dmitry89@newmail.mail

Choose another address for your account.
['anna_kuznetsova21@newmail.mail', 'dmitry89@newmail.mail', 'ivan_petrov83@newmail.mail', 'masha1995@newmail.mail', 'olga_ivanova@newmail.mail', 'sergey_smirnov@newmail.mail']

### keys in dictionaries can only be immutable objects like strings or tuples; values can be any other value (most of the time those are strings)

In [1]:
dictE = dict() #dictionaries can be initialised with dict function. dictE is an empty dictionary without any parameters
print("dictE={}".format(dictE))

dictA = { #create another dictionary by using dict literals. number of key value pairs where the key is separated from the value by a column, and pairs are separated from each other using commas
    "A": 1,
    "B": 2,
    "C": 3,
    "D": 4
}
print("dictA = {}".format(dictA))

dictE={}
dictA = {'A': 1, 'B': 2, 'C': 3, 'D': 4}

In [48]:
us_data = country_data[1]

us_data["mtCO2"]
type(us_data["mtCO2"])

float

In [49]:
us_data_half = us_data["mtCO2"]/2
us_data_half

2701000000.0

In [31]:
dictA["X"] = 2000 #assigns the new object in the dictionary
dictA["X"]
print("dictA = {}".format(dictA))

dictA = {'A': 100, 'B': 2, 'C': 3, 'D': 4, 'X': 2000}

In [ ]:
del dictA["X"]
dictA["X"] #cant acces element since it does not exist

KeyError: 'X'

In [ ]:
dictA["Y"] #can not access Y since it does not exist either

KeyError: 'Y'

In [39]:
print(dictA.get("A"))
print(dictA.get("Y")) #get method returns the default value if there is no such key. 
print(dictA.get("Y", "NA")) #we may specify the value

100
None
NA

In [42]:
print("B" in dictA) #use in operator to test whether it is in dictionary
print("Y" in dictA)

True
False

In [14]:
total_emissions = 0 

for point in country_data:
    total_emissions += point["mtCO2"]  #takes the value from the left part and adds the value from the right part

mean_emissions = total_emissions / len(country_data)
mean_emissions

155554897.34741783

In [ ]:
more_than_average_countries = []

for point in country_data:
    if point["mtCO2"] > mean_emissions:
        more_than_average_countries.append(point) #if the condition is True point is appended to the list N.B. mtCO2 is also a list

len(more_than_average_countries)

31

### start with the list. process each of its elements. append the result of our processing to some other list. we can use list comprehension instead of the code above to create more than average countries list. simplified syntax when we need to process elements of a list or some other collection one by one

In [ ]:
more_than_average_countries = [point for point in country_data if point["mtCO2"] > mean_emissions]

len(more_than_average_countries) #point is every point that specifies the condition

31

In [30]:
list1 = [1,2,3,4,5,6,7,8,9,10]

only_even = [point for point in list1 if point/2 % 2 == 0]

only_even

[4, 8]

### another collection is a set(). it is unordered collection where each element can be present at most once. repeated elements in a set are deleted

In [1]:
scandinavian_countries = set() #creates an empty set using set() function
print(scandinavian_countries)

scandinavian_countries.add("Sweden") #adds an element to a set
print(scandinavian_countries)

scandinavian_countries.add("Sweden") #if same element is added nothing changes since each element can be present at most once
print(scandinavian_countries)

scandinavian_countries.update(['Sweden', 'Denmark','Finland','Norway','Iceland']) #adds the collection of elements to the set
print(scandinavian_countries)

northern_europe = set(['Sweden', 'Denmark','Finland','Norway','Iceland','Netherlands','Luxembourg','Belgium']) #set() creates sets from other collection types 
print(northern_europe)

set()
{'Sweden'}
{'Sweden'}
{'Finland', 'Denmark', 'Sweden', 'Iceland', 'Norway'}
{'Luxembourg', 'Finland', 'Belgium', 'Denmark', 'Netherlands', 'Sweden', 'Iceland', 'Norway'}

In [8]:
print('scandinavian_countries =', scandinavian_countries)
print('northern_europe =', northern_europe)

print('scandinavian_countries & northern_europe = {}'.format(scandinavian_countries & northern_europe))
print('scandinavian_countries | northern_europe = {}'.format(scandinavian_countries | northern_europe))

print('scandinavian_countries - northern_europe = {}'.format(scandinavian_countries - northern_europe))
print('northern_europe - scandinavian_countries = {}'.format(northern_europe - scandinavian_countries))

print('scandinavian_countries ^ northern_europe = {}'.format(scandinavian_countries ^ northern_europe))

print('scandinavian_countries >= northern_europe = {}'.format(scandinavian_countries >= northern_europe))
print('scandinavian_countries <= northern_europe = {}'.format(scandinavian_countries <= northern_europe))
print('scandinavian_countries == northern_europe = {}'.format(scandinavian_countries == northern_europe))

scandinavian_countries = {'Finland', 'Denmark', 'Sweden', 'Iceland', 'Norway'}
northern_europe = {'Luxembourg', 'Finland', 'Belgium', 'Denmark', 'Netherlands', 'Sweden', 'Iceland', 'Norway'}
scandinavian_countries & northern_europe = {'Finland', 'Denmark', 'Sweden', 'Iceland', 'Norway'}
scandinavian_countries | northern_europe = {'Luxembourg', 'Finland', 'Belgium', 'Denmark', 'Netherlands', 'Sweden', 'Iceland', 'Norway'}
scandinavian_countries - northern_europe = set()
northern_europe - scandinavian_countries = {'Luxembourg', 'Belgium', 'Netherlands'}
scandinavian_countries ^ northern_europe = {'Luxembourg', 'Belgium', 'Netherlands'}
scandinavian_countries >= northern_europe = False
scandinavian_countries <= northern_europe = True
scandinavian_countries == northern_europe = False

### sets are unordered so the order in which you created a set is not the same as it is in your output. so to access individual elements in a set we can not use the indexes. those are not meaningful

In [ ]:
print('scandinavian_countries =', scandinavian_countries)
print('Russia in scandivian_countries = {}'.format("Russia" in scandinavian_countries)) #use in operator to test whether a country(string object) is a member of a set
print('Norway in scandinavian_countries = {}'.format("Norway" in scandinavian_countries))
print('Denmark in scandinavian_countries = {}'.format('Denmark' in scandinavian_countries))

scandinavian_countries = {'Finland', 'Denmark', 'Sweden', 'Iceland', 'Norway'}
Russia in scandivian_countries = False
Norway in scandinavian_countries = True
Denmark in scandinavian_countries = True

In [12]:
list(scandinavian_countries ^ northern_europe) #converts sets into lists

['Luxembourg', 'Belgium', 'Netherlands']

In [23]:
eastern_europe = set(['Ukraine','Belarus','Russia','Poland','Hungary'])


big_emitters = set([point['country'] for point in country_data if point['mtCO2'] > mean_emissions])
big_emitters & eastern_europe

{'Poland', 'Russia', 'Ukraine'}

### list ordered collection of elements but it is immutable. so we can not change the object in a tuple

In [24]:
tupleA = (1,2,3,4,5)
print(tupleA)

(1, 2, 3, 4, 5)

In [28]:
tupleA[0] = 10 #would not assign

TypeError: 'tuple' object does not support item assignment

In [33]:
print('this is list {}'.format(list(tupleA))) #converts a tuple into a list

print('this is tuple {}'.format(tuple(list1))) #tuples can be keys in dictionaries and members of sets

print('this is set {}'.format(set(tupleA)))

this is list [1, 2, 3, 4, 5]
this is tuple (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
this is set {1, 2, 3, 4, 5}

In [ ]:
permutation_a = (1,2) 
permutation_b = (2,1)

if permutation_a == permutation_b:
    print("combination")
else:
    print('permutation')

permutation

In [ ]:
set_sum_3 = set()

set_sum_3.add(permutation_a)
set_sum_3.add(permutation_b)

set_sum_3  #tuples can be elements in a set representing different elements in a set being different permutations

{(1, 2), (2, 1)}

In [ ]:
value = int(input("Enter a number: ")) + 1 #f string is the first way of formatting strings

print(f'Your number +1 is {value}') #convenient when you only need to use your template once in your code

Your number +1 is 5

In [ ]:
template = 'Your number +1 is {}' #define the template with the placeholder. we can use the template wherever we need to

value = int(input('Enter a number: ')) + 1

print(template.format(value)) #when using the template more than once a better way is .format method. call a format method on a template to add your data to the template

Your number +1 is 124

In [ ]:
stringT1 = 'The quick brown fox jumps over the lazy dog'
print(stringT1.split()) #converts each word separated by space to a list of strings

stringT2 = 'The;quick;brown;fox;jumps;over;the;lazy;dog'
print(stringT2.split(';')) #parameter in split method is a semicolumn (thing that separates the words)

['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

In [13]:
listJ1 = stringT1.split()

print('|'.join(listJ1))
print(' -> '.join(listJ1))
print(''.join(listJ1))

The|quick|brown|fox|jumps|over|the|lazy|dog
The -> quick -> brown -> fox -> jumps -> over -> the -> lazy -> dog
Thequickbrownfoxjumpsoverthelazydog

In [5]:
import pandas as pd

In [8]:
os.getcwd()

'D:\\py_programming\\data'

In [10]:
country_data_pd = pd.read_csv('./country_data.csv')#python has wide array of reading functions they start with read_ and then the name of the format
country_data_pd

,country,mtCO2,population,GDP
0,China,9.135000e+09,1373541278,2.114000e+13
1,United States,5.402000e+09,323995528,1.856000e+13
2,India,1.887000e+09,1266883598,8.721000e+12
3,Russia,1.756000e+09,142355415,3.751000e+12
4,Japan,1.257000e+09,126702133,4.932000e+12
...,...,...,...,...
208,Kiribati,5.845000e+04,106925,2.110000e+08
209,Falkland Islands (Islas Malvinas),4.557000e+04,2931,2.818000e+08
210,"Saint Helena, Ascension, And Tristan Da Cunha",1.208000e+04,7795,3.110000e+07
211,Niue,3.520000e+03,1190,1.001000e+07
212,"Micronesia, Federated States Of",1.050000e+02,104719,3.140000e+08

In [11]:
country_data_pd['mtCO2'] #subsetting the column

0      9.135000e+09
1      5.402000e+09
2      1.887000e+09
3      1.756000e+09
4      1.257000e+09
           ...
208    5.845000e+04
209    4.557000e+04
210    1.208000e+04
211    3.520000e+03
212    1.050000e+02
Name: mtCO2, Length: 213, dtype: float64

In [ ]:
type(country_data_pd['mtCO2']) #series are datatypes that suport vectorised arithmetic operations on that. it is extremely important when trying to subset our data based on their values

pandas.Series

In [ ]:
country_data_pd[['mtCO2','country']] #double parentheses are required. pandas are clunky

            mtCO2                                        country
0    9.135000e+09                                          China
1    5.402000e+09                                  United States
2    1.887000e+09                                          India
3    1.756000e+09                                         Russia
4    1.257000e+09                                          Japan
..            ...                                            ...
208  5.845000e+04                                       Kiribati
209  4.557000e+04              Falkland Islands (Islas Malvinas)
210  1.208000e+04  Saint Helena, Ascension, And Tristan Da Cunha
211  3.520000e+03                                           Niue
212  1.050000e+02                Micronesia, Federated States Of

[213 rows x 2 columns]

In [ ]:
is_big_emitter = country_data_pd['mtCO2'] > mean_emissions #returns a series of logical values. compared the each single value with mean_emissions
is_big_emitter

0       True
1       True
2       True
3       True
4       True
       ...
208    False
209    False
210    False
211    False
212    False
Name: mtCO2, Length: 213, dtype: bool

In [ ]:
country_data_pd[is_big_emitter] #put the logical series into the data set to subset a dataset

                 country         mtCO2  population           GDP
0                  China  9.135000e+09  1373541278  2.114000e+13
1          United States  5.402000e+09   323995528  1.856000e+13
2                  India  1.887000e+09  1266883598  8.721000e+12
3                 Russia  1.756000e+09   142355415  3.751000e+12
4                  Japan  1.257000e+09   126702133  4.932000e+12
5                Germany  7.440000e+08    80722792  3.979000e+12
6                   Iran  6.504000e+08    82801633  1.459000e+12
7           Korea, South  5.993000e+08    50924172  1.934000e+12
8           Saudi Arabia  5.940000e+08    28160273  1.731000e+12
9         United Kingdom  5.683000e+08    64430428  2.788000e+12
10                Canada  5.640000e+08    35362905  1.674000e+12
11                Brazil  5.350000e+08   205823665  3.081000e+12
12          South Africa  4.820000e+08    54300704  7.391000e+11
13                Mexico  4.550000e+08   123166749  2.307000e+12
14             Indonesia  4.420000e+08   258316051  3.033000e+12
15                France  3.856000e+08    66836154  2.699000e+12
16             Australia  3.850000e+08    22992654  1.189000e+12
17                 Italy  3.620000e+08    62007540  2.221000e+12
18                Turkey  3.190000e+08    80274604  1.698000e+12
19              Thailand  3.010000e+08    68200824  1.161000e+12
20                Poland  2.960000e+08    38523261  1.052000e+12
21               Ukraine  2.910000e+08    44209733  3.526000e+11
22                 Spain  2.760000e+08    48563476  1.690000e+12
23            Kazakhstan  2.578000e+08    18360353  4.688000e+11
24  United Arab Emirates  2.450000e+08     5927482  6.672000e+11
25              Malaysia  2.080000e+08    30949962  8.630000e+11
26                 Egypt  2.070000e+08    94666993  1.105000e+12
27             Singapore  2.050000e+08     5781728  4.879000e+11
28             Argentina  2.020000e+08    43886748  8.794000e+11
29             Venezuela  1.880000e+08    30912302  4.686000e+11
30           Netherlands  1.848000e+08    17016967  8.708000e+11

In [17]:
country_data_pd[country_data_pd['mtCO2'] > mean_emissions] #one liner at the expense of readability

                 country         mtCO2  population           GDP
0                  China  9.135000e+09  1373541278  2.114000e+13
1          United States  5.402000e+09   323995528  1.856000e+13
2                  India  1.887000e+09  1266883598  8.721000e+12
3                 Russia  1.756000e+09   142355415  3.751000e+12
4                  Japan  1.257000e+09   126702133  4.932000e+12
5                Germany  7.440000e+08    80722792  3.979000e+12
6                   Iran  6.504000e+08    82801633  1.459000e+12
7           Korea, South  5.993000e+08    50924172  1.934000e+12
8           Saudi Arabia  5.940000e+08    28160273  1.731000e+12
9         United Kingdom  5.683000e+08    64430428  2.788000e+12
10                Canada  5.640000e+08    35362905  1.674000e+12
11                Brazil  5.350000e+08   205823665  3.081000e+12
12          South Africa  4.820000e+08    54300704  7.391000e+11
13                Mexico  4.550000e+08   123166749  2.307000e+12
14             Indonesia  4.420000e+08   258316051  3.033000e+12
15                France  3.856000e+08    66836154  2.699000e+12
16             Australia  3.850000e+08    22992654  1.189000e+12
17                 Italy  3.620000e+08    62007540  2.221000e+12
18                Turkey  3.190000e+08    80274604  1.698000e+12
19              Thailand  3.010000e+08    68200824  1.161000e+12
20                Poland  2.960000e+08    38523261  1.052000e+12
21               Ukraine  2.910000e+08    44209733  3.526000e+11
22                 Spain  2.760000e+08    48563476  1.690000e+12
23            Kazakhstan  2.578000e+08    18360353  4.688000e+11
24  United Arab Emirates  2.450000e+08     5927482  6.672000e+11
25              Malaysia  2.080000e+08    30949962  8.630000e+11
26                 Egypt  2.070000e+08    94666993  1.105000e+12
27             Singapore  2.050000e+08     5781728  4.879000e+11
28             Argentina  2.020000e+08    43886748  8.794000e+11
29             Venezuela  1.880000e+08    30912302  4.686000e+11
30           Netherlands  1.848000e+08    17016967  8.708000e+11

### logical series support vectorised logical operations. you can easily build larger sets of expressions when the country emits more than average CO2 or has more population than average

In [21]:
country_data_pd['is_big_emitter'] = country_data_pd['mtCO2'] > mean_emissions
country_data_pd

,country,mtCO2,population,GDP,is_big_emitter
0,China,9.135000e+09,1373541278,2.114000e+13,True
1,United States,5.402000e+09,323995528,1.856000e+13,True
2,India,1.887000e+09,1266883598,8.721000e+12,True
3,Russia,1.756000e+09,142355415,3.751000e+12,True
4,Japan,1.257000e+09,126702133,4.932000e+12,True
...,...,...,...,...,...
208,Kiribati,5.845000e+04,106925,2.110000e+08,False
209,Falkland Islands (Islas Malvinas),4.557000e+04,2931,2.818000e+08,False
210,"Saint Helena, Ascension, And Tristan Da Cunha",1.208000e+04,7795,3.110000e+07,False
211,Niue,3.520000e+03,1190,1.001000e+07,False
212,"Micronesia, Federated States Of",1.050000e+02,104719,3.140000e+08,False

In [100]:
country_data_pd['co2_pcap'] = country_data_pd['mtCO2'] / country_data_pd['population']
country_data_pd['gdp_pcap'] = country_data_pd['GDP'] / country_data_pd['population']

country_data_pd

,country,mtCO2,population,GDP,is_big_emitter,co2_pcap,gdp_pcap
0,China,9.135000e+09,1373541278,2.114000e+13,True,6.650692,15390.873459
1,United States,5.402000e+09,323995528,1.856000e+13,True,16.673070,57284.741288
2,India,1.887000e+09,1266883598,8.721000e+12,True,1.489482,6883.821066
3,Russia,1.756000e+09,142355415,3.751000e+12,True,12.335323,26349.542095
4,Japan,1.257000e+09,126702133,4.932000e+12,True,9.920906,38925.942944
...,...,...,...,...,...,...,...
208,Kiribati,5.845000e+04,106925,2.110000e+08,False,0.546645,1973.345803
209,Falkland Islands (Islas Malvinas),4.557000e+04,2931,2.818000e+08,False,15.547595,96144.660525
210,"Saint Helena, Ascension, And Tristan Da Cunha",1.208000e+04,7795,3.110000e+07,False,1.549711,3989.737011
211,Niue,3.520000e+03,1190,1.001000e+07,False,2.957983,8411.764706
212,"Micronesia, Federated States Of",1.050000e+02,104719,3.140000e+08,False,0.001003,2998.500750

In [23]:
country_data_pd['mtCO2'].mean() #computes mean for a series

np.float64(155554897.34741783)

In [ ]:
country_data_pd.mean(numeric_only=True) #computes means for all columns

mtCO2             1.555549e+08
population        3.436917e+07
GDP               5.597426e+11
is_big_emitter    1.455399e-01
co2_pcap          6.552687e+00
gdp_pcap          2.107813e+04
dtype: float64

In [29]:
country_data_pd.describe()

              mtCO2    population           GDP    co2_pcap       gdp_pcap
count  2.130000e+02  2.130000e+02  2.130000e+02  213.000000     213.000000
mean   1.555549e+08  3.436917e+07  5.597426e+11    6.552687   21078.130282
std    7.537403e+08  1.328472e+08  2.100234e+12   12.560131   23634.300918
min    1.050000e+02  1.190000e+03  1.001000e+07    0.001003     436.243466
25%    1.400000e+06  9.153030e+05  9.066000e+09    0.701353    4489.327479
50%    9.100000e+06  6.237738e+06  5.479000e+10    3.053746   13350.221928
75%    6.200000e+07  2.346479e+07  3.011000e+11    7.548265   27987.036679
max    9.135000e+09  1.373541e+09  2.114000e+13  122.749591  148121.382484

In [ ]:
country_data_pd.groupby('is_big_emitter').describe() #groups by values in the column with logical values

                mtCO2                                                        \
                count          mean           std          min          25%
is_big_emitter
False           182.0  2.059886e+07  3.159927e+07        105.0     821925.0
True             31.0  9.478774e+08  1.802645e+09  184800000.0  266900000.0

                                                       population  \
                        50%          75%           max      count
is_big_emitter
False             5600000.0   24287500.0  1.450000e+08      182.0
True            385600000.0  596650000.0  9.135000e+09       31.0

                              ...   co2_pcap             gdp_pcap  \
                        mean  ...        75%         max    count
is_big_emitter                ...
False           1.331888e+07  ...   6.166812  122.749591    182.0
True            1.579548e+08  ...  12.051900   41.332896     31.0

                                                                       \
                        mean           std          min           25%
is_big_emitter
False           18924.214589  23050.947161   436.243466   3675.673893
True            33723.699836  23412.074340  6883.821066  16207.064096


                         50%           75%            max
is_big_emitter
False           10838.100280  25711.354604  148121.382484
True            27308.176221  45304.610146  112560.443035

[2 rows x 40 columns]

In [32]:
pd_descriptives = country_data_pd.groupby('is_big_emitter')[['co2_pcap','gdp_pcap']].describe()
pd_descriptives

               co2_pcap                                                      \
                  count       mean        std       min       25%       50%
is_big_emitter
False             182.0   5.929113  12.990910  0.001003  0.507112  2.173156
True               31.0  10.213669   8.966547  1.489482  5.143020  7.683669

                                      gdp_pcap                              \
                      75%         max    count          mean           std
is_big_emitter
False            6.166812  122.749591    182.0  18924.214589  23050.947161
True            12.051900   41.332896     31.0  33723.699836  23412.074340

                                                                       \
                        min           25%           50%           75%
is_big_emitter
False            436.243466   3675.673893  10838.100280  25711.354604
True            6883.821066  16207.064096  27308.176221  45304.610146


                          max
is_big_emitter
False           148121.382484
True            112560.443035

In [34]:
os.chdir('D:\py_programming')
from openpyxl import Workbook

pd_descriptives.to_excel('./environment_descriptives.xlsx')

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\SEMEN\AppData\Local\Temp\ipykernel_6024\2183411930.py:1: SyntaxWarning: invalid escape sequence '\p'
  os.chdir('D:\py_programming')

In [35]:
import numpy as np

In [ ]:
[1,1,1] + [2,2,2] #we would only have concatenation of them

[1, 1, 1, 2, 2, 2]

In [37]:
#array is similar to R's vectors and matrices. arrays can support arbitrary dimensions

print(np.array(3.14159265)) #0D array or a scalar. numpy object that just represents a number

print(np.array([1,2,3,4,5])) #1D array or a vector. can hold a lot of different kinds of numbers

big_array = np.array(range(100))
print(big_array)

3.14159265
[1 2 3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

In [ ]:
print(np.array([[1,2,3,4],[6,7,8,9]])) #Create a 2D array or a matrix

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\SEMEN\AppData\Local\Temp\ipykernel_6024\1155761822.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  print(np.array([[[1,2,3,4,5],[6,7,8,9,10]][1,2,3,4,5]])) #Create a 2D array or a matrix

TypeError: list indices must be integers or slices, not tuple

In [ ]:
matrix_1 = big_array.reshape(10,10) #reshaping functions includes arguments of dimensions 
print(matrix_1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

In [ ]:
matrix_2 = big_array.reshape(5,-1) #-1 could also be accepted. it will try to find the number of values by dividing the number of elements by the number of rows
print(matrix_2)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]

In [126]:
print(big_array.ndim) #number of dimensions
print(big_array.shape) #shape property of the array. holds the shape of the array (rows and columns)
print()
print(matrix_1.ndim)
print(matrix_2.shape)

1
(100,)

2
(5, 20)

In [ ]:
matrix_D = np.array([['0.5' , '0'], ['0' , '0.5']]) #when in a_ij i=j 0.5 those are diagonal elements

print(matrix_D)

[['0.5' '0']
 ['0' '0.5']]

In [ ]:
row_1 = matrix_D[0]
row_2 = matrix_D[1]

print('off_diagonal element in the matrix = {}'.format(row_1[1]))
print('diagonal element in the matrix = {}'.format(row_2[1]))

off_diagonal element in the matrix = 0
diagonal element in the matrix = 0.5

In [ ]:
matrix_1[2,-1] #select row, then column, negative indices (select the column fro the end). outputs the element in the row 2 column 10

np.int64(29)

In [ ]:
matrix_1[2] # this give us the third row of a matrix which is a sub array of a big one 1-D array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
matrix_1[2:5, 4:9] #we can also slice the matrix

array([[24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48]])

In [ ]:
for r in matrix_1: #iterate over rows and prints them
    print(r)
    for e in r:
        print(e) #iterates over elements in rows and prints them

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9
[10 11 12 13 14 15 16 17 18 19]
10
11
12
13
14
15
16
17
18
19
[20 21 22 23 24 25 26 27 28 29]
20
21
22
23
24
25
26
27
28
29
[30 31 32 33 34 35 36 37 38 39]
30
31
32
33
34
35
36
37
38
39
[40 41 42 43 44 45 46 47 48 49]
40
41
42
43
44
45
46
47
48
49
[50 51 52 53 54 55 56 57 58 59]
50
51
52
53
54
55
56
57
58
59
[60 61 62 63 64 65 66 67 68 69]
60
61
62
63
64
65
66
67
68
69
[70 71 72 73 74 75 76 77 78 79]
70
71
72
73
74
75
76
77
78
79
[80 81 82 83 84 85 86 87 88 89]
80
81
82
83
84
85
86
87
88
89
[90 91 92 93 94 95 96 97 98 99]
90
91
92
93
94
95
96
97
98
99

In [ ]:
for e in np.nditer(matrix_1[2:4, 4:7]): #it might work for multidimensional objects as well
    print(e)

24
25
26
34
35
36

In [101]:
numpy_emissions = np.array(country_data_pd['co2_pcap'])
numpy_gdp_pcap = np.array(country_data_pd['gdp_pcap'])
numpy_emissions

array([6.65069201e+00, 1.66730696e+01, 1.48948175e+00, 1.23353228e+01,
       9.92090638e+00, 9.21672779e+00, 7.85491755e+00, 1.17684780e+01,
       2.10935455e+01, 8.82036668e+00, 1.59489160e+01, 2.59931238e+00,
       8.87649633e+00, 3.69417886e+00, 1.71108221e+00, 5.76933257e+00,
       1.67444785e+01, 5.83799970e+00, 3.97385953e+00, 4.41343641e+00,
       7.68366935e+00, 6.58226097e+00, 5.68328346e+00, 1.40411244e+01,
       4.13328965e+01, 6.72052521e+00, 2.18661218e+00, 3.54565279e+01,
       4.60275617e+00, 6.08172112e+00, 1.08597496e+01, 7.17837631e-01,
       1.49064117e+00, 3.59146202e+00, 3.17904130e+00, 3.69822310e+00,
       3.77721359e+01, 9.67604780e+00, 5.21355736e-01, 8.20574706e+00,
       4.07389154e+01, 1.25568494e+01, 8.57497474e-01, 9.05671293e+00,
       7.24015300e+00, 3.51856152e+00, 4.30592120e+00, 1.56710416e+00,
       7.31423718e+00, 2.05647130e+01, 1.26622540e+01, 4.22570700e-01,
       7.64570231e+00, 6.27492004e+00, 8.71300108e+00, 7.91582102e+00,
       1.02371097e+01, 1.99081747e+00, 6.98704332e+00, 2.85129562e+00,
       3.93288209e+01, 5.50169733e+00, 4.47604727e+00, 4.05951144e+00,
       7.82072569e+00, 7.50833291e+00, 1.33372100e+00, 1.15879035e+00,
       2.36306975e+00, 8.26898979e+00, 2.68329050e+01, 3.54510616e+00,
       6.86525701e+00, 1.63590407e+00, 5.71082092e+00, 2.32558244e+00,
       1.06755710e+00, 8.03131365e-01, 2.07412841e+00, 1.88601500e+00,
       2.32121059e+00, 4.40456433e+00, 5.31014607e+00, 2.79252472e+01,
       4.40196462e+00, 4.58808943e+00, 7.19586238e-01, 1.45856991e+00,
       2.56503239e+00, 2.63664788e-01, 7.22941878e+00, 3.81164993e-01,
       4.61843481e+00, 8.95328348e-01, 2.77832644e-01, 4.37660335e+00,
       3.93281442e+00, 3.92399364e+00, 4.08796376e-01, 7.56171684e-01,
       1.88908982e+01, 1.90538883e-01, 1.12444718e+00, 1.64118953e+00,
       9.13055726e+01, 9.08433392e-02, 7.54826535e+00, 3.78889610e-01,
       1.92386973e+01, 3.76185998e+00, 1.56304418e+00, 3.86633470e+00,
       4.02332851e+00, 2.22008714e-01, 2.20828549e+00, 5.09774578e-01,
       1.42043956e+00, 2.66822075e-01, 4.07339046e-01, 1.33954001e+00,
       3.45116969e+00, 4.60849632e+00, 4.00521568e+00, 8.71489197e-01,
       4.65486157e-01, 1.41746796e+00, 1.99166398e+00, 7.01353167e-01,
       1.41512818e+00, 1.44658416e-01, 1.25261215e+01, 1.64172005e+00,
       1.50404066e-01, 5.68280174e-01, 4.44127234e-01, 5.44813326e-01,
       4.87194039e+00, 1.22749591e+02, 2.25650520e-01, 9.82499598e+00,
       1.22798203e-01, 1.11206378e+00, 7.04606858e-02, 9.07918868e+00,
       6.52654004e-01, 4.09679358e+00, 2.00270842e-01, 1.60884649e-01,
       1.02313794e-01, 2.32050357e-01, 2.12593320e+00, 3.01293049e+00,
       1.10604515e+01, 1.85730845e+00, 2.31006823e+00, 1.72135980e-02,
       7.17487576e-02, 1.15766112e-01, 2.32601105e-01, 1.50237160e+01,
       4.45976775e+00, 3.05374593e+00, 3.85530683e+00, 4.82868885e-02,
       8.31996438e-02, 7.91918908e+00, 2.13802638e+00, 4.58003695e-02,
       6.15933128e-02, 1.36289243e-01, 1.58553988e+01, 1.97819464e+00,
       1.39536701e-01, 4.13385990e-01, 6.41155790e+00, 8.50617406e+00,
       1.10713363e+01, 9.01468958e+00, 7.12344778e-02, 2.48799790e-01,
       2.84226724e-01, 3.96488067e-01, 4.49563474e+00, 8.73087937e+00,
       7.26314388e-02, 7.22762688e-01, 2.43214320e+00, 2.53111969e-02,
       2.70287364e-02, 1.53604325e-01, 4.72420858e-01, 5.11055841e-01,
       2.93111871e+00, 4.08853031e+00, 5.73295878e+00, 3.47008832e-01,
       2.51674263e-01, 7.20580500e-01, 1.00539899e+00, 1.87770507e+00,
       3.88878087e+00, 5.84248656e+00, 2.08528829e+01, 2.09292591e+01,
       3.57462020e+01, 5.06224024e-01, 1.35580352e+00, 1.67097019e+01,
       5.46644845e-01, 1.55475947e+01, 1.54971135e+00, 2.95798319e+00,
       1.00268337e-03])

In [102]:
array_test_1 = np.array([1,2,3,4]) #vectors or one dimensional arrays
array_test_2 = np.array([5,6,7,8])
array_test_3 = np.array([9,10,11,12])

print(np.concatenate([array_test_1,array_test_2,array_test_3])) #joining arrays along an axis

[ 1  2  3  4  5  6  7  8  9 10 11 12]

In [104]:
print(np.stack([array_test_1, array_test_2, array_test_3], axis=0)) #adds a dimensions and allows to treat individual arrays as either rows or columns

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

In [103]:
print(np.stack([array_test_1, array_test_2, array_test_3], axis=1))

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

In [105]:
col_1 = np.repeat(1,213) #creates an array of 213 value of 1

x = np.stack([col_1, numpy_gdp_pcap], axis = 1) #stacked column of ones with gdp_pcap
x

array([[1.00000000e+00, 1.53908735e+04],
       [1.00000000e+00, 5.72847413e+04],
       [1.00000000e+00, 6.88382107e+03],
       [1.00000000e+00, 2.63495421e+04],
       [1.00000000e+00, 3.89259429e+04],
       [1.00000000e+00, 4.92921504e+04],
       [1.00000000e+00, 1.76204254e+04],
       [1.00000000e+00, 3.79780353e+04],
       [1.00000000e+00, 6.14695745e+04],
       [1.00000000e+00, 4.32714804e+04],
       [1.00000000e+00, 4.73377399e+04],
       [1.00000000e+00, 1.49691242e+04],
       [1.00000000e+00, 1.36112416e+04],
       [1.00000000e+00, 1.87307047e+04],
       [1.00000000e+00, 1.17414307e+04],
       [1.00000000e+00, 4.03823356e+04],
       [1.00000000e+00, 5.17121686e+04],
       [1.00000000e+00, 3.58182247e+04],
       [1.00000000e+00, 2.11523934e+04],
       [1.00000000e+00, 1.70232547e+04],
       [1.00000000e+00, 2.73081762e+04],
       [1.00000000e+00, 7.97561931e+03],
       [1.00000000e+00, 3.47998154e+04],
       [1.00000000e+00, 2.55332781e+04],
       [1.00000000e+00, 1.12560443e+05],
       [1.00000000e+00, 2.78837176e+04],
       [1.00000000e+00, 1.16724950e+04],
       [1.00000000e+00, 8.43865363e+04],
       [1.00000000e+00, 2.00379395e+04],
       [1.00000000e+00, 1.51590134e+04],
       [1.00000000e+00, 5.11724563e+04],
       [1.00000000e+00, 4.89218722e+03],
       [1.00000000e+00, 6.24494671e+03],
       [1.00000000e+00, 1.56425211e+04],
       [1.00000000e+00, 1.51352169e+04],
       [1.00000000e+00, 6.86376635e+03],
       [1.00000000e+00, 1.06291496e+05],
       [1.00000000e+00, 3.29643221e+04],
       [1.00000000e+00, 5.85315873e+03],
       [1.00000000e+00, 4.45785404e+04],
       [1.00000000e+00, 1.48121382e+05],
       [1.00000000e+00, 5.96310826e+04],
       [1.00000000e+00, 7.86461604e+03],
       [1.00000000e+00, 4.78203626e+04],
       [1.00000000e+00, 2.69649288e+04],
       [1.00000000e+00, 2.04169162e+04],
       [1.00000000e+00, 2.47080557e+04],
       [1.00000000e+00, 1.45698333e+04],
       [1.00000000e+00, 1.73451910e+04],
       [1.00000000e+00, 5.15906060e+04],
       [1.00000000e+00, 1.79010254e+04],
       [1.00000000e+00, 4.02338527e+03],
       [1.00000000e+00, 3.63323774e+04],
       [1.00000000e+00, 5.04118979e+04],
       [1.00000000e+00, 1.38934152e+04],
       [1.00000000e+00, 1.42498776e+04],
       [1.00000000e+00, 6.92666773e+04],
       [1.00000000e+00, 1.59265398e+03],
       [1.00000000e+00, 2.00289643e+04],
       [1.00000000e+00, 2.92577845e+03],
       [1.00000000e+00, 3.56990985e+04],
       [1.00000000e+00, 6.06776086e+04],
       [1.00000000e+00, 2.70993269e+04],
       [1.00000000e+00, 2.74233936e+04],
       [1.00000000e+00, 4.10497160e+04],
       [1.00000000e+00, 4.73382513e+04],
       [1.00000000e+00, 1.33502219e+04],
       [1.00000000e+00, 8.40271566e+03],
       [1.00000000e+00, 1.13427348e+04],
       [1.00000000e+00, 3.90653896e+04],
       [1.00000000e+00, 4.81324298e+04],
       [1.00000000e+00, 1.67632877e+04],
       [1.00000000e+00, 6.50180223e+04],
       [1.00000000e+00, 9.36926876e+03],
       [1.00000000e+00, 3.09963528e+04],
       [1.00000000e+00, 1.18873041e+04],
       [1.00000000e+00, 4.80294153e+04],
       [1.00000000e+00, 2.68136358e+03],
       [1.00000000e+00, 1.52636995e+04],
       [1.00000000e+00, 1.17471792e+04],
       [1.00000000e+00, 1.05297442e+04],
       [1.00000000e+00, 2.18466391e+04],
       [1.00000000e+00, 3.66120597e+04],
       [1.00000000e+00, 1.64603818e+04],
       [1.00000000e+00, 1.10126797e+04],
       [1.00000000e+00, 2.51319346e+04],
       [1.00000000e+00, 1.06453789e+04],
       [1.00000000e+00, 7.17069434e+03],
       [1.00000000e+00, 1.36523849e+04],
       [1.00000000e+00, 5.40161262e+03],
       [1.00000000e+00, 3.45545996e+04],
       [1.00000000e+00, 4.79995631e+03],
       [1.00000000e+00, 1.22058634e+04],
       [1.00000000e+00, 8.67678502e+03],
       [1.00000000e+00, 3.26346498e+03],
       [1.00000000e+00, 8.54784301e+03],
       [1.00000000e+00, 8.61941827e+03],
       [1.00000000e+00, 2.99975300e+04],
       [1.00000000e+00, 4.48932748e+03],
       [1.00000000e+00, 1.94748580e+03],
       [1.00000000e+00, 1.00877396e+05],
       [1.00000000e+00, 2.86951558e+03],
       [1.00000000e+00, 4.85648737e+03],
       [1.00000000e+00, 3.66823319e+03],
       [1.00000000e+00, 3.68330565e+04],
       [1.00000000e+00, 1.70648724e+03],
       [1.00000000e+00, 2.42705763e+04],
       [1.00000000e+00, 3.66969015e+03],
       [1.00000000e+00, 7.72525308e+04],
       [1.00000000e+00, 1.40569755e+04],
       [1.00000000e+00, 1.62666599e+04],
       [1.00000000e+00, 2.57670859e+04],
       [1.00000000e+00, 9.81934320e+03],
       [1.00000000e+00, 1.92247546e+03],
       [1.00000000e+00, 2.18590422e+04],
       [1.00000000e+00, 2.77373236e+03],
       [1.00000000e+00, 7.56282604e+03],
       [1.00000000e+00, 3.17066724e+03],
       [1.00000000e+00, 3.69362514e+03],
       [1.00000000e+00, 6.23813477e+03],
       [1.00000000e+00, 2.06955142e+04],
       [1.00000000e+00, 3.09325451e+04],
       [1.00000000e+00, 1.91731158e+04],
       [1.00000000e+00, 5.62278126e+03],
       [1.00000000e+00, 2.26319369e+03],
       [1.00000000e+00, 5.28132153e+03],
       [1.00000000e+00, 1.62501675e+04],
       [1.00000000e+00, 8.89929134e+03],
       [1.00000000e+00, 1.11564757e+04],
       [1.00000000e+00, 2.46332616e+03],
       [1.00000000e+00, 2.76980044e+04],
       [1.00000000e+00, 1.06670760e+04],
       [1.00000000e+00, 1.35016573e+03],
       [1.00000000e+00, 9.42325099e+03],
       [1.00000000e+00, 3.09808754e+03],
       [1.00000000e+00, 4.12585659e+03],
       [1.00000000e+00, 4.18328503e+04],
       [1.00000000e+00, 6.96944899e+04],
       [1.00000000e+00, 4.20161268e+03],
       [1.00000000e+00, 4.80829349e+04],
       [1.00000000e+00, 1.53415888e+03],
       [1.00000000e+00, 7.86599780e+03],
       [1.00000000e+00, 2.21638002e+03],
       [1.00000000e+00, 3.91131448e+04],
       [1.00000000e+00, 4.54410350e+03],
       [1.00000000e+00, 1.45897061e+04],
       [1.00000000e+00, 1.84439909e+03],
       [1.00000000e+00, 1.66630529e+03],
       [1.00000000e+00, 1.14160655e+03],
       [1.00000000e+00, 1.49672480e+03],
       [1.00000000e+00, 3.95069252e+03],
       [1.00000000e+00, 1.05820814e+05],
       [1.00000000e+00, 2.99984024e+04],
       [1.00000000e+00, 9.14888294e+03],
       [1.00000000e+00, 8.22248403e+03],
       [1.00000000e+00, 7.99694582e+02],
       [1.00000000e+00, 1.69070822e+03],
       [1.00000000e+00, 1.32965649e+03],
       [1.00000000e+00, 1.76776840e+03],
       [1.00000000e+00, 2.79870367e+04],
       [1.00000000e+00, 1.64805571e+04],
       [1.00000000e+00, 1.37596702e+04],
       [1.00000000e+00, 1.92414859e+04],
       [1.00000000e+00, 1.08108978e+03],
       [1.00000000e+00, 4.36243466e+02],
       [1.00000000e+00, 2.21385330e+04],
       [1.00000000e+00, 3.93067371e+04],
       [1.00000000e+00, 2.18067009e+03],
       [1.00000000e+00, 1.69150635e+03],
       [1.00000000e+00, 1.56204508e+03],
       [1.00000000e+00, 3.96583162e+04],
       [1.00000000e+00, 8.72666437e+03],
       [1.00000000e+00, 8.80709144e+02],
       [1.00000000e+00, 7.53740454e+03],
       [1.00000000e+00, 2.31991537e+04],
       [1.00000000e+00, 7.36918213e+04],
       [1.00000000e+00, 1.31195335e+04],
       [1.00000000e+00, 3.76420455e+04],
       [1.00000000e+00, 5.83552842e+03],
       [1.00000000e+00, 1.68536978e+03],
       [1.00000000e+00, 1.62066078e+03],
       [1.00000000e+00, 3.94505627e+03],
       [1.00000000e+00, 1.35858082e+04],
       [1.00000000e+00, 4.37766292e+04],
       [1.00000000e+00, 5.82140982e+02],
       [1.00000000e+00, 6.47414678e+03],
       [1.00000000e+00, 1.26653857e+04],
       [1.00000000e+00, 2.58089838e+03],
       [1.00000000e+00, 7.11035959e+02],
       [1.00000000e+00, 3.08181478e+03],
       [1.00000000e+00, 1.88653396e+03],
       [1.00000000e+00, 1.54424040e+03],
       [1.00000000e+00, 1.21250611e+04],
       [1.00000000e+00, 2.45311819e+03],
       [1.00000000e+00, 2.72697739e+04],
       [1.00000000e+00, 8.57457090e+03],
       [1.00000000e+00, 1.58428949e+03],
       [1.00000000e+00, 2.60489851e+03],
       [1.00000000e+00, 5.25823673e+03],
       [1.00000000e+00, 5.22940862e+03],
       [1.00000000e+00, 1.22885475e+04],
       [1.00000000e+00, 1.46062164e+04],
       [1.00000000e+00, 1.57230737e+04],
       [1.00000000e+00, 2.55441607e+04],
       [1.00000000e+00, 3.84807864e+04],
       [1.00000000e+00, 3.51319473e+03],
       [1.00000000e+00, 1.10091246e+04],
       [1.00000000e+00, 8.31213214e+03],
       [1.00000000e+00, 1.97334580e+03],
       [1.00000000e+00, 9.61446605e+04],
       [1.00000000e+00, 3.98973701e+03],
       [1.00000000e+00, 8.41176471e+03],
       [1.00000000e+00, 2.99850075e+03]])

In [ ]:
print(array_test_1 + 1)
print(array_test_2 * 3) #support vectorised operations. numpy arrays and vectors are similar

[2 3 4 5]
[15 18 21 24]

In [ ]:
print('Dot product', np.dot(array_test_1, array_test_2)) #multipl each element of a matrix and then sum them up
print('Transportation', np.stack([array_test_1, array_test_2, array_test_3], axis = 1))

Dot pruduct 70
Transportation [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

In [129]:
m1 = np.matmul(x.T, x)
mli = np.linalg.inv(m1)
m2 = np.matmul(mli, x.T)

y_col = numpy_emissions.reshape((-1,1))
beta = np.matmul(m2, y_col)
beta

array([[3.13264683e-01],
       [2.96014009e-04]])

In [127]:
print(x.T.shape)
print(x.shape)
print(m1.shape)

(2, 213)
(213, 2)
(2, 2)

In [128]:
m1

array([[2.13000000e+02, 4.48964175e+06],
       [4.48964175e+06, 2.13052252e+11]])